export const SET_TILELAYER = "SET_TILELAYER";
export const SET_PLOTBOUNDRIES = "SET_PLOTBOUNDRIES";

export const SET_SELECTEDFEATURE = "SET_SELECTEDFEATURE";
export const ADD_FEATURE_START = "ADD_FEATURE_START";
export const ADD_FEATURE_SUCCESS = "ADD_FEATURE_SUCCESS";
export const ADD_FEATURE_FAIL = "ADD_FEATURE_FAIL";
export const ADD_FEATURE_INIT = "ADD_FEATURE_INIT";

export const GET_USER_FEATURES_START = "GET_USER_FEATURES_START";
export const GET_USER_FEATURES_SUCCESS = "GET_USER_FEATURES_SUCCESS";
export const GET_USER_FEATURES_FAIL = "GET_USER_FEATURES_FAIL";
export const GET_USER_FEATURES_INIT = "GET_USER_FEATURES_INIT";
