export const SET_TILELAYER = "SET_TILELAYER";
export const SET_PLOTBOUNDRIES = "SET_PLOTBOUNDRIES";

export const SET_SELECTEDFEATURE = "SET_SELECTEDFEATURE";
export const ADD_FEATURE_START = "ADD_FEATURE_START";
export const ADD_FEATURE_SUCCESS = "ADD_FEATURE_SUCCESS";
export const ADD_FEATURE_FAIL = "ADD_FEATURE_FAIL";
export const ADD_FEATURE_INIT = "ADD_FEATURE_INIT";

export const GET_USER_FEATURES_START = "GET_USER_FEATURES_START";
export const GET_USER_FEATURES_SUCCESS = "GET_USER_FEATURES_SUCCESS";
export const GET_USER_FEATURES_FAIL = "GET_USER_FEATURES_FAIL";
export const GET_USER_FEATURES_INIT = "GET_USER_FEATURES_INIT";

export const GET_FEATURE_START = "GET_FEATURE_START";
export const GET_FEATURE_SUCCESS = "GET_FEATURE_SUCCESS";
export const GET_FEATURE_FAIL = "GET_FEATURE_FAIL";
export const GET_FEATURE_INIT = "GET_FEATURE_INIT";

export const DELETE_FEATURE_START = "DELETE_FEATURE_START";
export const DELETE_FEATURE_SUCCESS = "DELETE_FEATURE_SUCCESS";
export const DELETE_FEATURE_FAIL = "DELETE_FEATURE_FAIL";
export const DELETE_FEATURE_INIT = "DELETE_FEATURE_INIT";

export const UPDATE_FEATURE_START = "UPDATE_FEATURE_START";
export const UPDATE_FEATURE_SUCCESS = "UPDATE_FEATURE_SUCCESS";
export const UPDATE_FEATURE_FAIL = "UPDATE_FEATURE_FAIL";
export const UPDATE_FEATURE_INIT = "UPDATE_FEATURE_INIT";

export const GET_PLOT_SHAPEFILE_START = "GET_PLOT_SHAPEFILE_START";
export const GET_PLOT_SHAPEFILE_SUCCESS = "GET_PLOT_SHAPEFILE_SUCCESS";
export const GET_PLOT_SHAPEFILE_FAIL = "GET_PLOT_SHAPEFILE_FAIL";
export const GET_PLOT_SHAPEFILE_INIT = "GET_PLOT_SHAPEFILE_INIT";
