export const SET_TILELAYER = "SET_TILELAYER";
export const SET_PLOTBOUNDRIES = "SET_PLOTBOUNDRIES";

export const SET_SELECTEDFEATURE = "SET_SELECTEDFEATURE";
export const ADD_FEATURE_START = "ADD_FEATURE_START";
export const ADD_FEATURE_SUCCESS = "ADD_FEATURE_SUCCESS";
export const ADD_FEATURE_FAIL = "ADD_FEATURE_FAIL";
export const ADD_FEATURE_INIT = "ADD_FEATURE_INIT";
